# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0002_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='date',
        ),
    ]
