# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0004_group_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='date',
        ),
        migrations.AddField(
            model_name='group',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
